[project]
name = "ai-infused-5-6"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "chromadb-client>=1.5.9",
    "fastapi[standard]>=0.141.1",
    "groq>=1.7.0",
    "joblib>=1.6.0",
    "onnxruntime>=1.30.0",
    "pandas>=3.0.5",
    "python-dotenv>=1.2.3",
    "scikit-learn>=1.9.0",
    "tokenizers>=0.23.2",
]
